a = int(input("Enter Your RollNo:"))
b = input("Enter Your Name:")
c = int(input("Enter Marks in English:"))
d = int(input("Enter Marks in Accountancy:"))
e = int(input("Enter Marks in BusinessStudies"))
Marks = int(c+d+e)
per = int((c+d+e)/3)
print("RollNo.:", a)
print("Name:", b)
print("English:", c)
print("Accountancy:", d)
print("BusinessStudies:", e)
print("Marks:", Marks)
print("Percent:", per)
